[pytest]

# объявляем маркеры
markers =
    smoke: Основа
    regression: Фулл



# делаем пред.условия
addopts =
    -sv
    # сохраняем результаты тестов в директории
    --alluredir=allure-results
    # чистим от старых результатов нашу директорию
    --clean-alluredir
    #Кол-во допустимых к падению тестов
    --maxfail=2
    # даем реран упавших тестов
    --reruns=2
;;    реран в случае аварий сервера или прерывания связи
;    --only-rerun TimeoutException
;    --only-rerun HTTPSConnectionPool
;    --only-rerun StaleElementReferenceException
;    --only-rerun InvalidSessionIDException




